package gms.shared.event.coi;

public enum DepthRestraintReason {
  FIXED_AT_DEPTH_FOUND_USING_DEPTH_PHASE_MEASUREMENTS,
  FIXED_AT_STANDARD_DEPTH_FOR_ECM,
  FIXED_AT_SURFACE,
  FIXED_BY_ANALYST,
  OTHER
}
