spring:
  application:
    name: ui-processing-configuration-manager
  processing:
    configuration-names: ui.analyst-settings, ui.common-settings

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /ui-processing-configuration-service

persistenceUnitName: gms_processing_configuration

springdoc:
  swagger-ui:
    disable-swagger-default-url: true