NAME = bitnami-zookeeper
SOURCE_IMAGE = $${IRONBANK_REGISTRY}/ironbank/bitnami/zookeeper
SOURCE_TAG = $${BITNAMI_ZOOKEEPER_TAG}

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.docker

build:
	$(MAKE) tag
