{{- $appName := "elasticsearch" }}

{{/* elasticsearch is a third-party chart, so this only adds an istio VirtualService */}}

{{- if .Values.global.istio }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $appName }}"
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
spec:
  hosts:
    - "{{ $appName }}.{{ .Values.global.baseDomain }}"
  gateways:
    - "istio-system/ingress-default-gateway"
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: "{{ $appName }}-master.{{ .Release.Name }}.svc.cluster.local"
            port:
              number: 9200
{{- end }}
