{{/* Main template for soh */}}

{{- include "gms.common.configMap.standard" $ }}
{{- include "gms.common.limitrange" $ }}
{{- include "gms.common.sidecar" $ }}
{{- include "gms.common.secrets.copy" $ }}
{{- include "gms.common.configMaps.copy" $ }}

{{- range $index, $appName := .Values.standardApps }}
{{- $appContext := mustMergeOverwrite (mustDeepCopy $) (dict "appValues" (get $.Values $appName)) (dict "appName" $appName) }}
{{- include "gms.common.app.standard" $appContext }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gms
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gms-psp-role
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gms-psp-bind
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gms-psp-role
subjects:
- kind: ServiceAccount
  name: gms
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
