# builder specific environment
# Any dependencies added here should also be added to the combined environment file in python/gms-test-environment.yml
# These dependencies are only for CI
#
# After making any changes to this file, a clean builder environment needs to be created, and the lock file regenerated:
# `conda env remove --name builder`
# `conda env create --name builder --file environment.yml`
# `conda env export --name builder --no-builds --channel conda-forge --override-channels | grep -v "prefix" > environment.lock.yml`
#

name: builder
channels:
  - conda-forge
dependencies:
  - coverage=6.3.1
  - flake8=4.0.1
  - markdown=3.3.6
  - matplotlib-base=3.5.1
  - minio=7.1.7
  - openpyxl=3.0.9
  - pandas=1.4.3
  - pip=22.0.4
  - pylint=2.13.5
  - pytest=7.1.1
  - pytest-mock=3.7.0
  - python=3.10.4
  - pyyaml=6.0
  - rich=12.5.1
  - tenacity=8.0.1
  - termcolor=1.1.0
  - twine=3.4.1
  - yapf=0.32.0
  - pip:
    - testcontainers==3.5.3
