export enum DataNames {
  MONITOR_THRESHOLDS = 'MONITOR_THRESHOLDS',
  CHANNEL_MONITOR_THRESHOLDS = 'CHANNEL_MONITOR_THRESHOLDS',
  STATION_CAPABILITY_ROLLUP = 'STATION_CAPABILITY_ROLLUP',
  CHANNEL_CAPABILITY_ROLLUP = 'CHANNEL_CAPABILITY_ROLLUP',
  TIMEWINDOWS = 'TIME_WINDOWS',
  STATION_GROUPS = 'STATION_GROUPS',
}
