SUBDIRS := bitnami \
           builder \
           logging \
           minio \
           postgres \
           postgres-exporter \
           prometheus \
           ubi

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.subdir
