CREATE TABLE GMS_GLOBAL.NETMAG (
  MAGID NUMBER(18,0),
	NET VARCHAR2(8 BYTE),
	ORID NUMBER(18,0) NOT NULL,
	EVID NUMBER(18,0),
	MAGTYPE VARCHAR2(6 BYTE),
	NSTA NUMBER(8,0),
	MAGNITUDE FLOAT(24),
	UNCERTAINTY FLOAT(24),
	AUTH VARCHAR2(15 BYTE),
	COMMID NUMBER(18,0),
	LDDATE DATE,
	CONSTRAINT NETMAG_PK PRIMARY KEY (MAGID)
)