CREATE SCHEMA IF NOT EXISTS GMS_GLOBAL AUTHORIZATION GMS_GLOBAL;

CREATE TABLE IF NOT EXISTS GMS_GLOBAL.ORIGERR
(
    "ORID" NUMBER(18,0),
    "SXX" FLOAT(24),
    "SYY" FLOAT(24),
    "SZZ" FLOAT(24),
    "STT" FLOAT(24),
    "SXY" FLOAT(24),
    "SXZ" FLOAT(24),
    "SYZ" FLOAT(24),
    "STX" FLOAT(24),
    "STY" FLOAT(24),
    "STZ" FLOAT(24),
    "SDOBS" FLOAT(24),
    "SMAJAX" FLOAT(24),
    "SMINAX" FLOAT(24),
    "STRIKE" FLOAT(24),
    "SDEPTH" FLOAT(24),
    "STIME" FLOAT(24),
    "CONF" FLOAT(24),
    "COMMID" NUMBER(18,0),
    "LDDATE" DATE,
    CONSTRAINT "ORIGERR_PK" PRIMARY KEY ("ORID")
);