CREATE SCHEMA IF NOT EXISTS GMS_GLOBAL AUTHORIZATION GMS_GLOBAL;

CREATE TABLE IF NOT EXISTS GMS_GLOBAL.ORIGIN
(
    "LAT" FLOAT(24),
	"LON" FLOAT(24),
	"DEPTH" FLOAT(24),
	"TIME" FLOAT(53),
	"ORID" NUMBER(18,0),
	"EVID" NUMBER(18,0),
	"JDATE" NUMBER(8,0),
	"NASS" NUMBER(4,0),
	"NDEF" NUMBER(4,0),
	"NDP" NUMBER(4,0),
	"GRN" NUMBER(8,0),
	"SRN" NUMBER(8,0),
	"ETYPE" VARCHAR2(7 BYTE),
	"DEPDP" FLOAT(24),
	"DTYPE" VARCHAR2(1 BYTE),
	"MB" FLOAT(24),
	"MBID" NUMBER(18,0),
	"MS" FLOAT(24),
	"MSID" NUMBER(18,0),
	"ML" FLOAT(24),
	"MLID" NUMBER(18,0),
	"ALGORITHM" VARCHAR2(15 BYTE),
	"AUTH" VARCHAR2(15 BYTE),
	"COMMID" NUMBER(18,0),
	"LDDATE" DATE,
	 CONSTRAINT ORIGIN_PK
            primary key (LAT, LON, DEPTH, TIME)
)