spring:
  application:
    name: signal-detection
  processing:
    configuration-names: signal-detection

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /signal-detection-manager-service

persistenceUnitName: gms_station_definition

signalDetectionPersistenceUnitName: gms_signal_detection

monitoringOrgConfig: global.monitoring-org
accountsByStageConfig: global.stage-accounts
orderedStagesConfig: workflow-manager.workflow-definition
waveformLeadLagConfig: signal-detection.waveform-lead-lag

springdoc:
  swagger-ui:
    disable-swagger-default-url: true