spring:
  application:
    name: waveform-manager
  processing:
    configuration-names: waveform-manager

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /waveform-manager-service

persistenceUnitName: gms_station_definition

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

