# gms-sysconfig specific environment
# Any dependencies added here should also be added to the combined environment file in python/gms-test-environment.yml
#
# After making any changes to this file, a clean gms-sysconfig environment needs to be created, and the lock file regenerated:
# `conda env remove --name gms-sysconfig`
# `conda env create --name gms-sysconfig --file environment.yml`
# `conda env export --name gms-sysconfig --no-builds --channel conda-forge --override-channels | grep -v "prefix" > environment.lock.yml`
#

name: gms-sysconfig
channels:
  - conda-forge
dependencies:
  - jproperties=2.1.1
  - pip=22.0.4
  - python=3.10.4
  - pip:
    - etcd3==0.12.0
