# gms-test-environment.yml
#
# This environment should include only direct requirements for running any python script in GMS
# Additions or updated requirements in this file may require a TPS, please check with IA.
#
# Please keep these lists in alphabetical order
# Only install from pip if package is not available in conda-forge channel
#
# Note the main channel is NOT available due to anaconda licensing! All packages must
# come from conda-forge or pip
#
# After making any changes to this file, a clean gms environment needs to be created, and the lock file regenerated:
# `conda env remove --name gms`
# `conda env create --name gms --file gms-test-environment.yml`
# `conda env export --name gms --no-builds --channel conda-forge --override-channels | grep -v "prefix" > gms-test-environment.lock.yml`
#

name: gms
channels:
  - conda-forge
dependencies:
  - coverage=6.3.1
  - cx_oracle=8.3.0
  - flake8=4.0.1
  - flask-executor=0.10.0
  - flask-sqlalchemy=2.5.1
  - flask=2.1.1
  - gunicorn=20.1.0
  - ipython=8.2.0
  - jproperties=2.1.1
  - markdown=3.3.6
  - matplotlib=3.5.1
  - minio=7.1.7
  - notebook=6.4.11
  - obspy=1.3.0
  - openpyxl=3.0.9
  - pip=22.0.4
  - pylint=2.13.5
  - pytest=7.1.1
  - pytest-mock=3.7.0
  - python=3.10.4
  - pyyaml=6.0
  - requests=2.27.1
  - sqlalchemy=1.4.35
  - rich=12.5.1
  - tenacity=8.0.1
  - termcolor=1.1.0
  - twine=4.0.0
  - yapf=0.32.0
  - pip:
    - etcd3==0.12.0
    - e1==0.1.0
    - pisces==0.3.2
    - testcontainers==3.5.3
