NAME = bitnami-kafka-exporter
SOURCE_IMAGE = $${IRONBANK_REGISTRY}/ironbank/bitnami/kafka-exporter
SOURCE_TAG = $${BITNAMI_KAFKA_EXPORTER_TAG}

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.docker

build:
	$(MAKE) tag
